-- treesitter
require('nvim-treesitter').setup {
  ensure_installed = {
    'bash',
    'css',
    'dart',
    'dockerfile',
    'elixir',
    'erlang',
    'glimmer',
    'glimmer_javascript',
    'glimmer_typescript',
    'go',
    'html',
    'java',
    'javascript',
    'json',
    'kotlin',
    'make',
    'markdown',
    'python',
    'ruby',
    'sql',
    -- 'swift',
    'toml',
    'typescript',
    'xml',
    'yaml',
  },
}
