require 'config.dotenv'
require 'config.options'
require 'config.lazy'

require 'setup.display'
require 'setup.finder'
require 'setup.lsp'
require 'setup.snippets'
require 'setup.cmp'
require 'setup.vcs'
require 'setup.format'
require 'setup.tester'
require 'setup.assistant'
require 'setup.keymaps'
