" Generated by vim-plug
" Wed 09 Mar 2022 21:02:20 +06
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '04ed87c8829015ff3653a35fb4f6d7a71668d736'
silent! let g:plugs['codi.vim'].commit = '73fc14f78d67fecc710a0dc312e87d83cf970605'
silent! let g:plugs['editorconfig-vim'].commit = '2c3e5323609d97ad7bda6fc22ae1f7746caab3d4'
silent! let g:plugs['emmet-vim'].commit = '0414b53a23c1da180370bf1228b8553fc5022e3f'
silent! let g:plugs['gitsigns.nvim'].commit = '5c487a804e462c284c159c800a803b8e0294d0a4'
silent! let g:plugs['nvim-autopairs'].commit = 'd2cde7c5802b34d6391a8a3555a3b7b56482f2aa'
silent! let g:plugs['nvim-treesitter'].commit = 'f735498a645e1a2aca7a0cfdaa2d7f8cec543846'
silent! let g:plugs['nvim-ts-autotag'].commit = '57035b5814f343bc6110676c9ae2eacfcd5340c2'
silent! let g:plugs['plenary.nvim'].commit = '2a278c8a12a399e25b78a43ebcd4f3996cd4e4b6'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '8ec164b541327202e5e74f99bcc5fe5845720e18'
silent! let g:plugs['telescope.nvim'].commit = 'df0b35c8bc0944164828ccba8ea17941423c6725'
silent! let g:plugs['tmuxline.vim'].commit = '3f9030402aa552a06a350d2adadcbc7ba3469518'
silent! let g:plugs['vim-abolish'].commit = '40e8b973971beb5da279a499231464ae1d959c8b'
silent! let g:plugs['vim-airline'].commit = 'a0298263b7fd55827839862ffd3a8d5b2a787a5c'
silent! let g:plugs['vim-airline-themes'].commit = '725789c110fbab52f8c18021f9d043839d7e31ed'
silent! let g:plugs['vim-bundler'].commit = 'a9966117fea4595f320a80163cc4adf2e2bc0e30'
silent! let g:plugs['vim-commentary'].commit = '141d9d32a9fb58fe474fcc89cd7221eb2dd57b3a'
silent! let g:plugs['vim-css-color'].commit = '741dd18a35e251ededc0687eea9b8d100d3b83b8'
silent! let g:plugs['vim-fugitive'].commit = 'a9100fafb8c6deb187ee1cfaa37a4a02018d6c9a'
silent! let g:plugs['vim-gtfo'].commit = '7b2177d68f9492af1be6d13bf65d28377dfbec6e'
silent! let g:plugs['vim-multiple-cursors'].commit = 'dd9289af03abafa76b28c503e20747ff7d7d89e5'
silent! let g:plugs['vim-repeat'].commit = '43d2678fa59d068c815d8298331c195e850ff5a7'
silent! let g:plugs['vim-solarized8'].commit = '9b74a5faf5f8f90f1729ef054af99072ba061985'
silent! let g:plugs['vim-surround'].commit = '597068870b8f093a8b2d11536c62ff31222ee8d0'
silent! let g:plugs['vim-test'].commit = '5aa77d57d22d453bd53f28a18f80e7bfecccf811'
silent! let g:plugs['vim-tmux'].commit = 'b19923f7ab00bfcaeb252e0a452d49ebe2e49d6d'
silent! let g:plugs['vim-tmux-navigator'].commit = '18b775fbccde5ff02e516c014290650bb40e257d'
silent! let g:plugs['vim-unimpaired'].commit = 'd6325994b3c16ce36fd494c47dae4dab8d21a3da'
silent! let g:plugs['vim-vinegar'].commit = 'c38ea2195a43747aedf0bb4b7eb5aa8870260296'
silent! let g:plugs['vimux'].commit = '37f41195e6369ac602a08ec61364906600b771f1'

PlugUpdate!

