" Generated by vim-plug
" Sun 17 Apr 2016 03:03:53 AM BDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = 'b647ef5'
silent! let g:plugs['editorconfig-vim'].commit = 'ef035f5'
silent! let g:plugs['neomake'].commit = 'efed015'
silent! let g:plugs['neoyank.vim'].commit = '40042cc'
silent! let g:plugs['rust.vim'].commit = 'b4ecf4e'
silent! let g:plugs['tlib_vim'].commit = '2bb17b7'
silent! let g:plugs['tmuxline.vim'].commit = '1e638ef'
silent! let g:plugs['unite.vim'].commit = '7d07791'
silent! let g:plugs['vim-addon-mw-utils'].commit = '0c5612f'
silent! let g:plugs['vim-airline'].commit = '410429a'
silent! let g:plugs['vim-airline-themes'].commit = '13bad30'
silent! let g:plugs['vim-bundler'].commit = 'b42217a'
silent! let g:plugs['vim-colors-solarized'].commit = '528a59f'
silent! let g:plugs['vim-commentary'].commit = '73e0d9a'
silent! let g:plugs['vim-dispatch'].commit = 'eb3e564'
silent! let g:plugs['vim-emblem'].commit = '53f2123'
silent! let g:plugs['vim-endwise'].commit = '0067ced'
silent! let g:plugs['vim-eunuch'].commit = 'd02b2d0'
silent! let g:plugs['vim-fugitive'].commit = 'e1ae9ef'
silent! let g:plugs['vim-gitgutter'].commit = '28353bd'
silent! let g:plugs['vim-gtfo'].commit = '1362ed7'
silent! let g:plugs['vim-multiple-cursors'].commit = '47c9e3f'
silent! let g:plugs['vim-node'].commit = '13b3121'
silent! let g:plugs['vim-rails'].commit = 'eb388f0'
silent! let g:plugs['vim-repeat'].commit = '7a6675f'
silent! let g:plugs['vim-sensible'].commit = '9e91be7'
silent! let g:plugs['vim-snipmate'].commit = '71250b0'
silent! let g:plugs['vim-snippets'].commit = 'b66ede5'
silent! let g:plugs['vim-startify'].commit = 'c381ab7'
silent! let g:plugs['vim-surround'].commit = '2d05440'
silent! let g:plugs['vim-test'].commit = 'df8f558'
silent! let g:plugs['vim-tmux'].commit = '876f0bd'
silent! let g:plugs['vim-tmux-navigator'].commit = '1298b71'
silent! let g:plugs['vim-unimpaired'].commit = '11dc568'
silent! let g:plugs['vim-vinegar'].commit = '75fc382'
silent! let g:plugs['vimux'].commit = '2285cef'

PlugUpdate!

