#!/bin/sh
# Generated by vim-plug
# Sun 20 Mar 2016 08:44:26 PM BDT

vim +PlugUpdate +qa

PLUG_HOME=~/.vim/plugged

cd $PLUG_HOME/auto-pairs/ && git reset --hard b647ef5
cd $PLUG_HOME/editorconfig-vim/ && git reset --hard 5a3f8ac
cd $PLUG_HOME/neomake/ && git reset --hard e3f6fc5
cd $PLUG_HOME/neoyank.vim/ && git reset --hard a9a44e0
cd $PLUG_HOME/tlib_vim/ && git reset --hard 9734d8d
cd $PLUG_HOME/tmuxline.vim/ && git reset --hard 1e638ef
cd $PLUG_HOME/unite.vim/ && git reset --hard c9ce3b1
cd $PLUG_HOME/vim-addon-mw-utils/ && git reset --hard 0c5612f
cd $PLUG_HOME/vim-airline-themes/ && git reset --hard 5a6453c
cd $PLUG_HOME/vim-airline/ && git reset --hard dbb4d32
cd $PLUG_HOME/vim-bundler/ && git reset --hard b42217a
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-commentary/ && git reset --hard e0f4850
cd $PLUG_HOME/vim-emblem/ && git reset --hard 53f2123
cd $PLUG_HOME/vim-eunuch/ && git reset --hard eb8b2d5
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 9835920
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 4510e9b
cd $PLUG_HOME/vim-gtfo/ && git reset --hard b03debc
cd $PLUG_HOME/vim-multiple-cursors/ && git reset --hard 92622cf
cd $PLUG_HOME/vim-node/ && git reset --hard 13b3121
cd $PLUG_HOME/vim-rails/ && git reset --hard fc5d779
cd $PLUG_HOME/vim-repeat/ && git reset --hard 7a6675f
cd $PLUG_HOME/vim-sensible/ && git reset --hard 680a5c6
cd $PLUG_HOME/vim-snipmate/ && git reset --hard 7f91de3
cd $PLUG_HOME/vim-snippets/ && git reset --hard 0fc7fd1
cd $PLUG_HOME/vim-startify/ && git reset --hard 8545f6f
cd $PLUG_HOME/vim-surround/ && git reset --hard 2d05440
cd $PLUG_HOME/vim-test/ && git reset --hard cfa3be9
cd $PLUG_HOME/vim-tmux-navigator/ && git reset --hard 1298b71
cd $PLUG_HOME/vim-tmux/ && git reset --hard 876f0bd
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 11dc568
cd $PLUG_HOME/vim-vinegar/ && git reset --hard 75fc382
cd $PLUG_HOME/vimux/ && git reset --hard 2285cef
