# Dont allow accidental bashrc overwrite
set -o noclobber

# Disable Age old software control flow
stty -ixon

# Default editor
alias vim='nvim'
export VISUAL=vim
export EDITOR="$VISUAL"

# Httpie
alias http='http --style solarized'
